-- Fix Chandra Bhagat medicines - add composition from CSV
-- Run this on the server database

UPDATE medicines SET composition = 'AZITHROMYCIN INJ' WHERE name = 'AZOCIN' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFEPIME INJ' WHERE name = 'CEP-1000' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFEPIME & TAZOBACTAM INJ' WHERE name = 'CBTAZ' AND composition IS NULL;
UPDATE medicines SET composition = 'POLYMYXIN B INJ' WHERE name = 'CBMYX' AND composition IS NULL;
UPDATE medicines SET composition = 'FOSFOMYSIN SODIUM  INJ' WHERE name = 'CBFOS' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFUROXIME SODIUM INJ' WHERE name = 'CEFROX' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFTAZIDIME INJ' WHERE name = 'CEFZIDIME' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFTAZIDIME & TAZOBACTAM INJ' WHERE name = 'CEFZIDIME TZ' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFTRIAXONE & SULBACTAM INJ' WHERE name = 'CEZONE PLUS' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFTRIAXONE INJ' WHERE name = 'CEZONE' AND composition IS NULL;
UPDATE medicines SET composition = 'IMIPENEM & CILASTATIN INJ' WHERE name = 'CIMISPECT' AND composition IS NULL;
UPDATE medicines SET composition = 'AMOXYCILLIN & CLAVULANATE POTASSIUM INJ' WHERE name = 'CLAUVMENTIN' AND composition IS NULL;
UPDATE medicines SET composition = 'COLISTIMETHATE SODIUM INJ' WHERE name = 'COLISTIN' AND composition IS NULL;
UPDATE medicines SET composition = 'DORIPENEM INJ' WHERE name = 'DENEM' AND composition IS NULL;
UPDATE medicines SET composition = 'DOXYCYCLINE INJ' WHERE name = 'DOXYGUARD' AND composition IS NULL;
UPDATE medicines SET composition = 'CLARITHROMYCIN INJ' WHERE name = 'KLARINTON' AND composition IS NULL;
UPDATE medicines SET composition = 'MEROPENEM &SULBACTAM INJ' WHERE name = 'MEPLIFE S' AND composition IS NULL;
UPDATE medicines SET composition = 'MEROPENEM INJ' WHERE name = 'MEROSPECT' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFOPERAZONE & SULBACTAM INJ' WHERE name = 'NUEZANE FORTE' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFOPERAZONE  INJ' WHERE name = 'NUPERAZONE' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFOPERAZON 1 G & SULBACTAM 1 G' WHERE name = 'NUPERAZONE PLUS 2 G' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFOPERAZONE 2 G  & SULBACTAM 1 G  INJ' WHERE name = 'NUPERAZONE 3G' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFOPERAZONE 1 G  & SULBACTAM 500 INJ' WHERE name = 'NUPERAZONE FORTE' AND composition IS NULL;
UPDATE medicines SET composition = 'PIPERACILLIN TAZOBACTAM INJ' WHERE name = 'PIPTAL' AND composition IS NULL;
UPDATE medicines SET composition = 'PIPERACILLIN TAZOBACTAM INJ' WHERE name = 'PITALIN-COMBIPACK' AND composition IS NULL;
UPDATE medicines SET composition = 'TEICOPLANIN INJ' WHERE name = 'TECON' AND composition IS NULL;
UPDATE medicines SET composition = 'TICARCILLIN AND CLAVULANIC ACID INJ' WHERE name = 'TICARNATE' AND composition IS NULL;
UPDATE medicines SET composition = 'TIGECYCLINE INJ' WHERE name = 'TIGEGUARD' AND composition IS NULL;
UPDATE medicines SET composition = 'TIGECYCLINE INJ' WHERE name = 'TIGEMOR' AND composition IS NULL;
UPDATE medicines SET composition = 'VANCOMYCIN HCL INJ.' WHERE name = 'VANACIN-CP' AND composition IS NULL;
UPDATE medicines SET composition = 'CASPOFUNGIN ACETATE INJ' WHERE name = 'CASFUNGEN*' AND composition IS NULL;
UPDATE medicines SET composition = 'PRALIDOXIME CHORIDE INJ' WHERE name = 'CLOPAM' AND composition IS NULL;
UPDATE medicines SET composition = 'ASCORBIC ACID INJECTION IP' WHERE name = 'CBIC' AND composition IS NULL;
UPDATE medicines SET composition = 'ENOXAPARIN SODIUM INJ' WHERE name = 'MAXIPARINE' AND composition IS NULL;
UPDATE medicines SET composition = 'HEPARIN SODIUM INJ' WHERE name = 'THROMBOPARIN' AND composition IS NULL;
UPDATE medicines SET composition = 'ARTESUNATE INJ' WHERE name = 'FALSUN' AND composition IS NULL;
UPDATE medicines SET composition = 'ACYCLOVIR INJ' WHERE name = 'HERZOVIR' AND composition IS NULL;
UPDATE medicines SET composition = 'PARACETAMOL INFUSION INJ' WHERE name = 'CBMOL' AND composition IS NULL;
UPDATE medicines SET composition = 'METHYL PREDNISOLONE SODIUM SUCCINATE INJ' WHERE name = 'MPSS' AND composition IS NULL;
UPDATE medicines SET composition = 'HYDROCORTISONE SODIUM SUCCINATE INJ' WHERE name = 'MULTICORT' AND composition IS NULL;
UPDATE medicines SET composition = 'LEVETIRICETAM INJ' WHERE name = 'CBCETAM' AND composition IS NULL;
UPDATE medicines SET composition = 'MANNITOL WITH GLYCERIN INJ' WHERE name = 'MANNIGYL' AND composition IS NULL;
UPDATE medicines SET composition = 'ESOMEPRAZOLE SODIUM INJ' WHERE name = 'ANTACER' AND composition IS NULL;
UPDATE medicines SET composition = 'RABEPRAZOLE SODIUM INJ' WHERE name = 'CBRAB' AND composition IS NULL;
UPDATE medicines SET composition = 'PANTOPRAZOLE INJ' WHERE name = 'PANPROZOLE' AND composition IS NULL;
UPDATE medicines SET composition = 'SUCCINYL CHOLINE CHLORIDE INJ' WHERE name = 'SCOLAX*' AND composition IS NULL;
UPDATE medicines SET composition = 'PROPOFOL 1% W/V' WHERE name = 'NEWPOL' AND composition IS NULL;
UPDATE medicines SET composition = 'FERRIC CARBOXYMALTOSE INJECTION' WHERE name = 'CBHAEMO' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFUROXIME AXETIL TAB' WHERE name = 'CEFROX-500' AND composition IS NULL;
UPDATE medicines SET composition = 'AMOXYCILLIN & POTASSIUM CLAVULANATE TAB' WHERE name = 'CLAUVMENTIN-625' AND composition IS NULL;
UPDATE medicines SET composition = 'RABEPRAZOLE 20MG (EC)+DOMPERIDON 30 MG CAPS (SR) TAB' WHERE name = 'CBRAB-DSR' AND composition IS NULL;
UPDATE medicines SET composition = 'TRYPSIN IP 48 MG BROMELAIN 90 MG  RUTOSIDE TRIHYDRATE TAB' WHERE name = 'CB-RYSIN' AND composition IS NULL;
UPDATE medicines SET composition = 'FAROPENEM SODIUM 200MG POTASSIUM CLAVULANATE 125 MG TAB' WHERE name = 'CBPENIN' AND composition IS NULL;
UPDATE medicines SET composition = 'CEFUROXIME 500MG + CLAVULANIC ACID 125 MG TAB' WHERE name = 'CBXIME' AND composition IS NULL;
UPDATE medicines SET composition = 'COLLAGEN PEPTIDE  TYPE II 40 MG SODIUM NYALURONATE 30 MG CHONDROTIN  SULPHATE  200 MG VITAMIN C 35 MG TAB' WHERE name = 'CBSHINE' AND composition IS NULL;
UPDATE medicines SET composition = 'GLUCOSAMINE SULPHATE POTASSIUN CHLORIDE, METHYL SULPHONYL METHANE & DIACEREIN TAB' WHERE name = 'CBAMINE' AND composition IS NULL;
UPDATE medicines SET composition = 'FLUDROCORTISONE ACETATE 100 MCG' WHERE name = 'CB-FLOCORT' AND composition IS NULL;
UPDATE medicines SET composition = 'HYDROCORTISONE TAB' WHERE name = 'CBHYCOT' AND composition IS NULL;
UPDATE medicines SET composition = 'PRAZIQUANTEL TABS' WHERE name = 'DISTOSIDE' AND composition IS NULL;
UPDATE medicines SET composition = 'LEVOCETIRIZINE HYDROCHLORIDE 5MG  & MONTELUKAST SODIUM 10 MG TAB' WHERE name = 'LEVONAST' AND composition IS NULL;
UPDATE medicines SET composition = 'PYRIDOSTIGMINE BROMIDE TABS' WHERE name = 'MUSTONE(ALUALU STRIP)' AND composition IS NULL;
UPDATE medicines SET composition = 'ATRACURIUM BESYLATE INJ' WHERE name = 'ATCURIUM' AND composition IS NULL;
UPDATE medicines SET composition = 'VASOPRESSIN INJ' WHERE name = 'ARGIPRESS' AND composition IS NULL;
UPDATE medicines SET composition = 'PRALIDOXIME IODIDE INJ' WHERE name = 'CBC-PAM' AND composition IS NULL;
UPDATE medicines SET composition = 'PHYTOMENADIONE INJECTION IP' WHERE name = 'CBDIONE' AND composition IS NULL;
UPDATE medicines SET composition = 'THIAMINE HCL(VIT B1) INJ' WHERE name = 'CBCHLORIDE' AND composition IS NULL;
UPDATE medicines SET composition = 'ADRENALINE BITARTRATE  INJ' WHERE name = 'CBC-AD' AND composition IS NULL;
UPDATE medicines SET composition = 'AMIODARONE STERILE CONCENTRATE INJ' WHERE name = 'CBRONE' AND composition IS NULL;
UPDATE medicines SET composition = 'ADENOSINE INJ' WHERE name = 'CBCINE' AND composition IS NULL;
UPDATE medicines SET composition = 'MAGNESIUM SULPHATE INJ' WHERE name = 'CBCMG' AND composition IS NULL;
UPDATE medicines SET composition = 'POTASSIUM CHLORID FOR INJ CONCE USP' WHERE name = 'CBLITE' AND composition IS NULL;
UPDATE medicines SET composition = 'CALCIUM GLUCONATE & CALCIUM LACTOBIONATE INJ' WHERE name = 'CBIONATE' AND composition IS NULL;
UPDATE medicines SET composition = 'PIRACETAM INJ' WHERE name = 'CBRAC' AND composition IS NULL;
UPDATE medicines SET composition = 'MECOBALAMIN,PYRIDOXINE HCL & NIACINAMIDE INJ' WHERE name = 'CBCOXIDE' AND composition IS NULL;
UPDATE medicines SET composition = 'DOBUTAMINE HCL INJ' WHERE name = 'DOBIER S' AND composition IS NULL;
UPDATE medicines SET composition = 'DOPAMINE HCL INJ' WHERE name = 'DOPACEF' AND composition IS NULL;
UPDATE medicines SET composition = 'IRON SUCROSE INJ' WHERE name = 'FEROFER' AND composition IS NULL;
UPDATE medicines SET composition = 'GLYCOPYRROLATE INJ' WHERE name = 'GLYPROLATE' AND composition IS NULL;
UPDATE medicines SET composition = 'L-ORNITHINE L-ASPARTATE INFUSION INJ' WHERE name = 'HEPNOTEL' AND composition IS NULL;
UPDATE medicines SET composition = 'DEXAMETHASONE SODIUM INJ' WHERE name = 'HYTISONE' AND composition IS NULL;
UPDATE medicines SET composition = 'TERLIPRESSIN INJ' WHERE name = 'LITPRESS*' AND composition IS NULL;
UPDATE medicines SET composition = 'ACETYLCYSTEINE SOLUTION INJ' WHERE name = 'MUFOST' AND composition IS NULL;
UPDATE medicines SET composition = 'CITICOLINE SODIUM INJ' WHERE name = 'MYOCHOLINE' AND composition IS NULL;
UPDATE medicines SET composition = 'EDARAVONE INJ' WHERE name = 'NEUROVON' AND composition IS NULL;
UPDATE medicines SET composition = 'NITROGLYCERIN INJ.' WHERE name = 'NITROVIR' AND composition IS NULL;
UPDATE medicines SET composition = 'NORADRENALINE BITARTRATE INJ' WHERE name = 'NOREPIRIN' AND composition IS NULL;
UPDATE medicines SET composition = 'CLINDAMYCIN INJ' WHERE name = 'SAMCY' AND composition IS NULL;
UPDATE medicines SET composition = 'ONDANSETRON INJ' WHERE name = 'SANTRON' AND composition IS NULL;
UPDATE medicines SET composition = 'SODIUM BICARBONATE INJ' WHERE name = 'SOCARAB' AND composition IS NULL;
UPDATE medicines SET composition = 'TRANEXAMIC ACID INJ' WHERE name = 'TRAMIC' AND composition IS NULL;
UPDATE medicines SET composition = 'OCTREOTIDE INJ' WHERE name = 'V-STAT*' AND composition IS NULL;

SELECT 'Composition update completed' AS status;
